# local_backend: true
backend:
  name: gitlab
  repo: xrsweb/new-wix
  branch: master
display_url: xrsheffield.org
site_url: https://xrsheffield.org
logo_url: https://xrsheffield.org/img/hourglass-logo.svg

publish_mode: editorial_workflow

media_folder: "assets/img"
public_folder: "/img"

collections:
  - name: "events" # Used in routes, e.g., /admin/collections/blog
    label: "Events" # Used in the UI
    folder: "content/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    editor:
      preview: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", hint: 'The main title for the event'}
      - {label: "Link Title", name: "linktitle", widget: "string", required: false, hint: 'If the above title is long, provide a shortened version here to appear in links'}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Event Date", name: "expirydate", widget: "datetime", hint: 'Also the expiry date for the page. Set the time to late in the day, say 23.59'}
      - {label: "Time of the event", name: "event_time", widget: "string", hint: "For example 2pm - 6pm. This will show up on the page. The time from Event Date above will not.", required: false}
      - {label: "Summary", name: "summary", widget: "string", hint: 'A summary of the event appears in the listing of all events'}
      - {label: "Cover Image", name: "cover_image", widget: "image", required: false, hint: 'Use JPEGs only'}
      - label: "Location of event"
        name: "location"
        widget: "object"
        # summary: '{{fields.name}}: {{fields.birthdate}}'
        fields:
          - {label: "Name", name: "name", widget: "string", required: false}
          - {label: "Street", name: "street", widget: "string", required: false}
          - {label: "Town", name: "town", widget: "string", required: false}
          - {label: "Postcode", name: "postcode", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    editor:
      preview: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link Title", name: "linktitle", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Image", name: "cover_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
        
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "/"
        editor:
          preview: true
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - {label: "Date", name: "date", widget: "datetime"}
          - {label: "Description", name: "description", widget: "string"}
          - { label: "Body", name: "body", widget: "markdown"}

      - file: "content/get-involved.md"
        label: "Get Involved"
        name: "get-involved"
        editor:
          preview: true
        fields:
          - { label: "Title", name: "title", widget: "string"}
          # - {label: "Date", name: "date", widget: "datetime"}
          - { label: "Body", name: "body", widget: "markdown"}
            
      - file: "content/who-we-are.md"
        label: "Who We Are"
        name: "who-we-are"
        editor:
          preview: true
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - {label: "Date", name: "date", widget: "datetime"}
          - { label: "Body", name: "body", widget: "markdown"}
            
      - file: "layouts/shortcodes/monday-meetings.html"
        label: "Monday Meetings"
        name: "monday-meetings"
        editor:
          preview: true
        fields:
          - { label: "Body", name: "body", widget: "text"}